services:
  # A web service
  - type: web
    name: stock-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DASH_DEBUG
        value: false